### ISSUE TITLE
Love the repository, but quick issue.

### ISSUE THREAD

**Issue by JakubHojsan** [konstantinmuenster/gatsby-theme-portfolio-minimal#1]
I see there is a Medium integration in the src/section/Articles/

How does this piece of code work exactly, and where does it have a place to pull from a specific user's Medium feed?

I can't see how it is integrated with the Markdown exactly. 

It is not put in the example so is it useable?

Thank you for anyone who could answer this question!

**Comment by konstantinmuenster** [comment]
Hey 👋  Yes, you can definitely use it! All you have to do is to provide a URL to your Medium profile in the settings.json file. This profile URL will be used to fetch the articles ([see here](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/gatsby-theme-portfolio-minimal/src/sections/Articles/data.tsx#L35)).

You can then just add the Articles section to your page and define Medium as a source ([as in the example here](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/example-site/src/pages/index.js#L19)).

Hope this helps 🙂
