### ISSUE TITLE
How to comment out or remove cta button for the resume

### ISSUE THREAD

**Issue by will-sherman** [konstantinmuenster/gatsby-theme-portfolio-minimal#12]
In order to remove elements in the navigation and the footer I was able to remove the label text in the settings.json file.

However, the when removing the text "Resume" from the ctaButton designed for the resume button, the border remains. I tried commenting out the cta button but got the following error: 

 ERROR #11321  PLUGIN

"gatsby-transformer-json" threw an error while running the onCreateNode lifecycle:

Unable to parse JSON: file C:/Users/...settings.json

  80 |   } catch {
  81 |     const hint = node.absolutePath ? `file ${node.absolutePath}` : `in node ${node.id}`;
> 82 |     throw new Error(`Unable to parse JSON: ${hint}`);
     |           ^
  83 |   }
  84 |
  85 |   if (_.isArray(parsedContent)) {

File: node_modules\gatsby-transformer-json\gatsby-node.js:82:11

  Error: Unable to parse JSON: file C:/Users/...settings.json

  - gatsby-node.js:82 Object.onCreateNode
    [mysite]/[gatsby-transformer-json]/gatsby-node.js:82:11

  - api-runner-node.js:487 runAPI
    [mysite]/[gatsby]/src/utils/api-runner-node.js:487:16

**Comment by will-sherman** [comment]
update. I tried shadowing both as:

`{project root}\src\gatsby-theme-portfolio-minimal\content\settings.example.json`

`{project root}\src\gatsby-theme-portfolio-minimal\content\settings.json`

Each time, I removed:
`"ctaButton": { "openNewTab": true, "label": "Resume", "url": "/resume.pdf" },`

That didn't cause errors. But each time I removed or commented out the ctaButton section from:

`{project root}\src\content\settings.json`

the same error occurred. 

thanks in advance. Just figuring out the mechanics. It's otherwise a beautiful portfolio theme.

**Comment by konstantinmuenster** [comment]
Hey @will-sherman! Thanks for opening this. Just to make sure I understood it correctly: You want to remove the CTA button entirely so that the navigation bar starts at the very right? I think this doesn't work out of the box but shouldn't be too hard to implement/adjust.

**Comment by will-sherman** [comment]
thank you @konstantinmuenster and forgive my late reply. Yes that's correct. I would like just to remove that button.

**Comment by konstantinmuenster** [comment]
@will-sherman Alright, no problem. This will need some adjustments. I try to fix it soon - if you or someone else like to do it, feel free to open a PR for it 😊

**Comment by renishya7** [comment]
Hi @konstantinmuenster Thanks for this awesome theme. I was playing around with it for my project and wanted to remove the Resume CTA altogether. Will you be looking into this issue any time soon? 🙏

**Comment by tahunic** [comment]
Hi, I created a pull request [here](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/pull/28).

**Comment by konstantinmuenster** [comment]
Hey @will-sherman, @renishya7! Thanks to @tahunic for adding this. I will release a new theme version later 👏
