### ISSUE TITLE
pass through user-specified Interests Button label

### ISSUE THREAD

**Issue by artlu99** [konstantinmuenster/gatsby-theme-portfolio-minimal#15]
Thank you very much Konstantin for your theme. Am loving it! ❤️

I submitted a pull request for your review to allow the user to specify the button label in the Interests section. It currently appears hard-coded to a fixed phrase.

**Comment by konstantinmuenster** [comment]
Hey @artlu99! Sorry, I totally forgot to review your PR although I already had it opened a few days ago 😅 I will check it tomorrow and leave you some feedback. But already big thanks for contributing 😍

**Comment by konstantinmuenster** [comment]
Merged it!

**Comment by artlu99** [comment]
Awesome, thanks again for the brilliant theme! 👍❤️🚀
