### ISSUE TITLE
Updating tab name and updating favicon.

### ISSUE THREAD

**Issue by Jae-YS** [konstantinmuenster/gatsby-theme-portfolio-minimal#16]
Hi! I've been using this theme for some time now and love it. I was trying to see if there was a way to update the favicon and the title name on the tab part of google and was coming up with challenges. Is there a way to change these two things? Thank you very much!

**Comment by konstantinmuenster** [comment]
Hi there! Love to hear that ☺️  

You can take a look at [this part of the documentation](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal#customization).

For the tab part: You can set a default title in the `settings.json` file or in the page component directly (as in the [example site](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/example-site/src/pages/index.js#L16) implementation).

For the favicon: you can set this in your `gatsby-config.js` [like this](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal#configuring-gatsby-configjs). Basically, just need to set a correct path for the `favicon` property. I think there is an example in the example-site too.

Hope this helps!
