### ISSUE TITLE
Overlaps wrapping logo text on mobile 

### ISSUE THREAD

**Issue by willcode4food** [konstantinmuenster/gatsby-theme-portfolio-minimal#22]
Hello,

I noticed that when the logo text wraps on mobile, it overlaps. 

![image](https://user-images.githubusercontent.com/1649493/205151269-e62f0ec1-f145-4b4d-b589-ae1da05740f7.png)

The overlap is also visible in the header

![image](https://user-images.githubusercontent.com/1649493/205151390-db9eae3e-8b82-41f5-88e5-4493998e9847.png)

**Comment by konstantinmuenster** [comment]
Thanks a lot! Just merged your PR and will release a new theme version later 😊
