### ISSUE TITLE
As a user on mobile, I don't know that there is more than one project in the slider

### ISSUE THREAD

**Issue by demondragong** [konstantinmuenster/gatsby-theme-portfolio-minimal#25]
When viewing the website on a mobile device* only the first project is visible in the Projects section. As a user, I do not know that I can to scroll to the right to see more projects. I noticed this observing a few first-time viewers but issue #5 suggests this issue can even confuse the person who made the website...

<img src="https://user-images.githubusercontent.com/24405137/207041447-45245711-a99d-4ac3-bcf6-8776823d2c35.jpg" width=300px>

Suggested fix: "always" show a portion of the second project to hint that there is more than one project to see.

<img src="https://user-images.githubusercontent.com/24405137/207041531-31a4ce83-ed12-48fe-b2a7-1e64ad6eaa45.jpg" width=300px>

Currently projects appear with a fade up animation as soon as the space they would occupy on the screen goes above a certain threshold. The suggested fix would make the second project appear at the same time as the first one on mobile devices.

This issue is different but related to #9. It looks like both could be fixed with a modification of the onScreen threshold. I'm going to try different values to see if I can find one that solves both issues without negatively impacting the overall theme UX.

*Issue experienced on the following devices : pixel 6a, iPhone 11, Xiaomi Redmi note 10s. All using Chrome.

**Comment by konstantinmuenster** [comment]
Hey @demondragong and thanks for opening this up!

Yeah, looks like #9 definitely plays its part in this. Besides that, we need to consider that we choose a good width for the first item (so that it leaves space for the second, even on narrow devices). Feel free to play with it and open a PR – I am always happy about contributions! :)

**Comment by konstantinmuenster** [comment]
This should be fixed in v4.1.0 😊
