### ISSUE TITLE
Does gatsby theme minimal support a side bar or CSS Grid?

### ISSUE THREAD

**Issue by Josh-BI-UK** [konstantinmuenster/gatsby-theme-portfolio-minimal#26]
I would like to use this theme. I'm new to web dev and Gatsby so please forgive me for asking otherwise obvious questions.

I would like each page to have sidebar which could display a tag cloud, sereach bar, possiblly an add block. Does your template support this. Does your template make use of CSS Grids?

**Comment by konstantinmuenster** [comment]
Hey @Josh-BI-UK! Thanks for your question. The mentioned features are currently not supported. You could however extend the theme on your own - but it requires a bit of Gatsby knowledge.

Since I don't plan on integrating them into the core theme, I will close this here for now 👌

**Comment by Josh-BI-UK** [comment]
Thank you, makes sense. I will create a folk and have a go👍🏾

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
