### ISSUE TITLE
External links behavior with regards to SEO (target="_blank" and nofollow noopener noreferrer)

### ISSUE THREAD

**Issue by demondragong** [konstantinmuenster/gatsby-theme-portfolio-minimal#29]
Hi!

I'm not an SEO expert so I might be missing something but I notice all external links (mainly social profiles and projects) have the following attribute settings:

`target="_blank" rel="nofollow noopener noreferrer"`

My understanding is that target="_blank" and noopener together are for UX (forcing a new tab) and security purposes. I know there's debate online whether to do this or not. Maybe a separate issue.

But I'm wondering if the choice to have nofollow and noreferrer is also intentional as I would imagine people linking to their own products and online profiles could prefer to not have these (for SEO and analytics purposes).

**Comment by konstantinmuenster** [comment]
Hey @demondragong and thanks double checking that! It was certainly intentional for social profiles but I agree that it does not make sense to have `nofollow` as a default for project links. 

Making it optional for everything besides social profiles sounds good to me 👍

**Comment by konstantinmuenster** [comment]
Hey @demondragong !

I just published a new version that removes the `nofollow` attribute. I kept the `noreferrer` as it might be a security concern on older browser.

**Comment by demondragong** [comment]
Thank you! I think it's time for me to update my portfolio then :)
