### ISSUE TITLE
Add logo in the place of text for Main logo

### ISSUE THREAD

**Issue by chandu231** [konstantinmuenster/gatsby-theme-portfolio-minimal#32]
I am trying to add logo image instead of plain text:

"siteConfiguration": {
    "logo": { "text":"Portfolio"},"

I was not able to figure out how to insert a image in a responsive way. Could you please help.

Appreciate the wonderful template.

**Comment by konstantinmuenster** [comment]
Hey @chandu231 and thanks for opening the issue! Using a logo is not supported yet but a great idea. I leave this issue open in case anyone wants to submit a PR for it. That would be awesome!

**Comment by nikhilk218** [comment]
Would love to see this as well!

**Comment by konstantinmuenster** [comment]
Hey @chandu231 and @nikhilk218,

I just published a new version that includes the option to add a logo. You can check out the docs to see how it works:
https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal#configuring-settingsjson

Have fun with it 👋
