### ISSUE TITLE
In ArticlesSection, how to pull articles from blog instead of Medium?

### ISSUE THREAD

**Issue by ajh30117** [konstantinmuenster/gatsby-theme-portfolio-minimal#35]
I don't use Medium, so how can I show the latest articles directly from the site's internal blog page instead of feeding them from Medium?

Thanks!

<img width="668" alt="image" src="https://user-images.githubusercontent.com/90249218/227762405-f2d6f8d1-182e-442f-a7f3-ecc63da36db2.png">

**Comment by konstantinmuenster** [comment]
Hi @ajh30117! You can take a look here:

https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/example-site/src/pages/index.js#L19

Hope that helps :)
