### ISSUE TITLE
Issue with overriding `--page-width` in `globalStyles/theme.css`

### ISSUE THREAD

**Issue by unkdrew** [konstantinmuenster/gatsby-theme-portfolio-minimal#38]
Hi,

Im trying to override `--page-width` via `globalStyles/theme.css` as below:

```
:root {
  --page-width: 105rem;
}
```

Although the page width can be adjusted successfully, it broke a few other styling, e.g. burger becomes invisible when viewing on a mobile device, `darkTheme/lightTheme` both only display light theming colors.

**Comment by konstantinmuenster** [comment]
Hey @unkdrew! Thanks for opening this up! This could very well be. It's probably easy to fix since it is only a styling issue, but definitely needs some consideration. If you like, feel free to open a PR for it. I don't know when I get to fixing this.

**Comment by unkdrew** [comment]
Actually, I was able to override page width and page padding via [global.css](https://github.com/naw-db/naw-db.github.io/blob/develop/src/gatsby-theme-portfolio-minimal/globalStyles/global.css), instead of via `theme.css`.

One caveat though, is that I have to override the whole `global.css` instead of just overriding the specific entries.
