### ISSUE TITLE
Theme customization not working

### ISSUE THREAD

**Issue by ad-world** [konstantinmuenster/gatsby-theme-portfolio-minimal#4]
Hi!

I'm trying to customize the theme by using the concept of shadowing as defined in the readme. I have created a file called `theme.css` in the following directory.

`{project root}/src/globalStyles`

However, when I change any of the hex values, the style does not seem to change. When I check chrome developer tools, it still shows that the styles for the body are the default ones provided in the readme. 

How can I fix this?

**Comment by konstantinmuenster** [comment]
Hey @ad-world !

If I remember it correctly, it has to be `{project root}/src/gatsby-theme-portfolio-minimal/src/globalStyles`. Then, it will override the theme file from the `gatsby-theme-portfolio-minimal` node module package.

Let me know if it works 🤞

**Comment by ad-world** [comment]
Hi @konstantinmuenster!

Thank you for the fast response!

I moved the `theme.css` file to to `{project root}/src/gatsby-theme-portfolio-minimal/src/globalStyles`. The changes in the theme are still not being applied to the webpage when I use the 'gatsby develop' command. 
Is there some other setting that I need to toggle?

**Comment by konstantinmuenster** [comment]
Forget what I said 😄 it has to be `{project root}/src/gatsby-theme-portfolio-minimal/globalStyles/theme.css`

That's indeed a mistake in the documentation, I will update it - thanks a lot ☺️

**Comment by ad-world** [comment]
Hi!
It wasn't working at first but it started working after I cleared the gatsby cache. Thank you for your help!
