### ISSUE TITLE
Logo image becomes very large when comparing gatsby develop vs gatsby build

### ISSUE THREAD

**Issue by YibinLong** [konstantinmuenster/gatsby-theme-portfolio-minimal#49]
### Description:
Under "logo" in the "siteConfiguration" section, you can make the logo an "image" instead of "text". 

After running gatsby develop, the logo appears as normal in the webpage and the startup animation is normal. However, after running gatsby build, the logo becomes very large in both the startup animation and in the webpage itself.

### Relevant Settings:
```json
"siteConfiguration": {
    "logo": { "image": "../content/images/react.png"},
    ...
}
```

Adding "text" also doesn't work:

```json
"siteConfiguration": {
    "logo": { "text": "Portfolio",
              "image": "../content/images/react.png"},
   ...
}
```

#### After gatsby develop:

[gatsby_develop_example.webm](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/assets/22416363/4cd629b3-75fc-4bdc-9711-f8631657c5b6)

#### After gatsby build, gatsby serve:

[gatsby_build_example.webm](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/assets/22416363/574a8794-db94-4265-ac27-c3ba680b9490)

**Comment by konstantinruge** [comment]
Hey @YibinLong and thanks for opening this up! I just released a new version that should fix this: https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/releases/tag/v4.6.4

Hope it works 🙌

**Comment by YibinLong** [comment]
Thanks @konstantinmuenster! 

Just wondering, what would I have to do to have this change reflected on the website that I previously worked on? I previously used this to setup my Gatsby site: https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal#set-up-a-new-gatsby-site-with-portfolio-minimal, would I have to follow the section after it, "Add Portfolio Minimal To An Existing Gatsby Site", or is there a better way? Thanks!

**Comment by konstantinruge** [comment]
> Thanks @konstantinmuenster!
> 
> Just wondering, what would I have to do to have this change reflected on the website that I previously worked on? I previously used this to setup my Gatsby site: https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal#set-up-a-new-gatsby-site-with-portfolio-minimal, would I have to follow the section after it, "Add Portfolio Minimal To An Existing Gatsby Site", or is there a better way? Thanks!

Inside your `package.json` file, you find an entry for the theme (like [here](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/example-site/package.json#L16)). You just need to adjust the version of the theme to `4.6.4` and consecutively run `npm install` to install the update.
