### ISSUE TITLE
Miltiple InterestsSection with different content?

### ISSUE THREAD

**Issue by Alchantness** [konstantinmuenster/gatsby-theme-portfolio-minimal#50]
Hey! Great theme!!! 
Is it possible to use the same section (for example, InterestsSection) several times, but use different interests.json for the content? Thank you!

**Comment by konstantinruge** [comment]
Hey @Alchantness! At the moment, it is not yet possible. Since we already have an open issue for this (#21), I am closing this one in favor of the other. But thanks for signaling interest 😄
