### ISSUE TITLE
Extending routing with auth ❔

### ISSUE THREAD

**Issue by pat-ladon** [konstantinmuenster/gatsby-theme-portfolio-minimal#52]
Hi,

Got a question.

Is there a way to extend the routing with authentication? Any tips would be appreciated.

**Comment by konstantinruge** [comment]
Hey! What do you want to use the authentication for? Some further details would help to evaluate the feasibility.

Usually, I'd only like to extend the core theme with features that are helpful for most users. But perhaps you could override some theme functionality to add the authentication.

**Comment by pat-ladon** [comment]
Thanks for getting back. I would like to see whether I can modify the theme to have blog articles available to authenticated users only. I wonder whether this would be very complicated or somehow feasible. I am testing how to use firebase auth specifically.

**Comment by konstantinruge** [comment]
> Thanks for getting back. I would like to see whether I can modify the theme to have blog articles available to authenticated users only. I wonder whether this would be very complicated or somehow feasible. I am testing how to use firebase auth specifically.

Hm, this sounds rather complicated. Have you looked into theme shadowing? That way you could override the theme's functionality.

Since the use-case is quite specific, I don't see this included in the core theme.
