### ISSUE TITLE
Open link in same tab

### ISSUE THREAD

**Issue by yathAg** [konstantinmuenster/gatsby-theme-portfolio-minimal#53]
Hi,

Firstly, thank you for this fantastic theme! 

I apologize in advance if this is a really silly question. This is my first time using React or any SSG.

I'd like the button in the `ProjectsSection` to be redirected to a page in the same tab. Currently, it opens the correct page but is in a new tab.

The `index.tsx ` for the `ProjectsSection` does have the variable `externalLink={True}`.
Setting this to `false` followed by `gatsby clean` and `gatsby develop`, does the trick, but to my understanding, changes in `index.tsx` will not show up when I host this on Netlify.

![Screenshot from 2024-04-06 11-13-06](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/assets/58807660/c7f64f94-2b27-419e-874c-0cd63a84a09d)
> Button in question

What would be the solution to this?

Thanks for the help!!

**Comment by konstantinruge** [comment]
hey @yathAg and sorry for the late reply!

What you are looking for is called "theme shadowing". You can find out more about it on the Gatsby docs: https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/

Hope that helps!
