### ISSUE TITLE
Adding a Toggle button

### ISSUE THREAD

**Issue by RusiraJayatilake** [konstantinmuenster/gatsby-theme-portfolio-minimal#58]
I want to add a toggle button for dark and light modes in the Navbar. How can I do that?

**Comment by konstantinruge** [comment]
Hey @RusiraJayatilake!

You could extend or customize the theme via "shadowing". That's a Gatsby specific concept. If you search for it on Google, you'll find some tutorials on how to do it.

Hope that helps!

**Comment by RusiraJayatilake** [comment]
Okay, Thank you for the info.
