### ISSUE TITLE
License

### ISSUE THREAD

**Issue by anselmdk** [konstantinmuenster/gatsby-theme-portfolio-minimal#6]
Hi Konstantin,
your theme looks promising. I'd like to use it.
However, I see you don't have a license file. Would you mind adding one, so I know at what terms I'll be using it?
You should be able to add a standard one (e.g. MIT) directly through Github.

**Comment by konstantinmuenster** [comment]
Hey @anselmdk ! Thanks for the hint - I added a license. Have fun with the theme! ✌️

**Comment by anselmdk** [comment]
Awesome, thanks!
