### ISSUE TITLE
Load more interests button

### ISSUE THREAD

**Issue by cyoung43** [konstantinmuenster/gatsby-theme-portfolio-minimal#8]
Hi @konstantinmuenster ! 

I recently came across Gatsby and have been thrilled to implement it for my personal site. I found your portfolio theme and love it! Thanks for providing this awesome resource.

The one thing I have encountered is the `load more` interests button in `content/interests/interest.json`. I've changed the `"visible"` field to `false` but after saving and refreshing the browser, the button remains on the page. I've also tried `gatsby clean` and relaunching the development server but still no luck.

Do you have any suggestions for this piece?

Thanks!

**Comment by konstantinmuenster** [comment]
Hey @cyoung43! Happy to hear that you like the theme! And thanks for opening this issue. I looked it up and indeed there wasn't even an implementation for the `visible` prop 😅  I fixed it and released it - please upgrade to v3.2.2 and it should hopefully work 😊
